version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-app
    container_name: todo-app-container
    volumes: []
    working_dir: /app
    networks:
      - todo-network
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
networks:
  todo-network:
    driver: bridge