import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Inter } from 'next/font/google'
import './globals.css'
import { StyledRoot } from './StyledRoot';
import { Box, Typography } from '@mui/material';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppRouterCacheProvider>
      <StyledRoot>
        {/* header */}
        <Box bgcolor="black" color="white" sx={{paddingY: ["1rem", "1.5rem"]}}>
          <Typography variant='h5' fontWeight={700} textAlign={'center'}>
          Todo App
          </Typography>
          </Box>
        {children}
        </StyledRoot>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
